# ç«™ç‚¹åŸºç¡€ä¿¡æ¯
baseURL: https://www.coderclub.com.cn
title: Coder Club
paginate: 10
theme: PaperMod
publishDir: docs

enableRobotsTXT: true 
buildDrafts: false
buildFuture: false
buildExpired: false

# è¯­è¨€
defaultContentLanguage: zh-cn
languages:
  zh-cn:
    languageName: "ç®€ä½“ä¸­æ–‡"

# HTMLå‹ç¼©é€‰é¡¹
minify:
  disableXML: true
  minifyOutput: true

# ç½‘ç«™å‚æ•°
params:
  env: production
  title: Coder Club # ç½‘ç«™æ ‡é¢˜
  description: This is an example site for PaperMod theme # ç½‘ç«™æè¿°
  keywords: [Blog, Portfolio, PaperMod] # å…³é”®å­—
  author: pm0915 # ä½œè€…
  DateFormat: "2023-01-01" # æ—¥æœŸæ ¼å¼
  defaultTheme: auto
  disableThemeToggle: false # æ˜¯å¦ç¦ç”¨ä¸»é¢˜åˆ‡æ¢

  ShowReadingTime: true # æ˜¯å¦æ˜¾ç¤ºé˜…è¯»æ—¶é—´
  ShowShareButtons: true # æ˜¯å¦æ˜¾ç¤ºåˆ†äº«æŒ‰é’®
  ShowPostNavLinks: true # æ˜¯å¦æ˜¾ç¤ºä¸Šä¸‹ç¯‡æ–‡ç« é“¾æ¥
  ShowBreadCrumbs: true # æ˜¯å¦æ˜¾ç¤ºé¢åŒ…å±‘å¯¼èˆª
  ShowCodeCopyButtons: false # æ˜¯å¦æ˜¾ç¤ºä»£ç å¤åˆ¶æŒ‰é’®
  ShowWordCount: true # æ˜¯å¦æ˜¾ç¤ºå­—æ•°ç»Ÿè®¡
  ShowRssButtonInSectionTermList: true # æ˜¯å¦åœ¨æ–‡ç« åˆ—è¡¨æ˜¾ç¤ºrssæŒ‰é’®
  UseHugoToc: true # æ˜¯å¦å¼€å¯ç›®å½•
  disableSpecial1stPost: false # æ˜¯å¦ç¦ç”¨ç‰¹æ®Šçš„ç¬¬ä¸€ç¯‡æ–‡ç« 
  disableScrollToTop: false # æ˜¯å¦ç¦ç”¨æ»šåŠ¨åˆ°é¡¶éƒ¨æŒ‰é’®
  comments: false # æ˜¯å¦å¯ç”¨è¯„è®º
  hidemeta: false # æ˜¯å¦éšè—æ–‡ç« å…ƒæ•°æ®
  hideSummary: false # æ˜¯å¦éšè—æ–‡ç« æ‘˜è¦
  showtoc: false # æ˜¯å¦æ˜¾ç¤ºç›®å½•
  tocopen: false # æ˜¯å¦é»˜è®¤æ‰“å¼€ç›®å½•

  # ç«™ç‚¹å›¾æ ‡
  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon.ico"
    favicon32x32: "favicon_32.ico"
    apple_touch_icon: "favicon_32.ico"
    safari_pinned_tab: "favicon_32.ico"

  # æ ‡ç­¾
  label:
    text: "Coder Club"

  # ç¤¾äº¤åª’ä½“å›¾æ ‡åŠé“¾æ¥
  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"

  #ç»Ÿè®¡ä»£ç 
  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  # å°é¢
  cover:
    hidden: true # æ˜¯å¦éšè—
    hiddenInList: true # æ˜¯å¦éšè—åœ¨åˆ—è¡¨
    hiddenInSingle: true

  # ç¼–è¾‘æ–‡ç« 
  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # ç¼–è¾‘æ–‡å­—
    appendFilePath: true # è¿½åŠ æ–‡ä»¶è·¯å¾„åˆ°ç¼–è¾‘é“¾æ¥

  # æœç´¢é€‰é¡¹
  fuseOpts:
    isCaseSensitive: false # æ˜¯å¦åŒºåˆ†å¤§å°å†™
    shouldSort: true # æ˜¯å¦æ’åº
    location: 0 # ä½ç½®
    distance: 1000 # è·ç¦»
    threshold: 0.4 # é˜ˆå€¼
    minMatchCharLength: 0 # æœ€å°åŒ¹é…å­—ç¬¦é•¿åº¦
    keys: ["title", "permalink", "summary", "content"] # æœç´¢å…³é”®å­—

  # copyright ä¿¡æ¯
  StartYear: 2023
  FilingNo: é™•ICPå¤‡2023002394å·-1 # å·¥ä¿¡éƒ¨å¤‡æ¡ˆå·
  PublicSecurityIconLink: https://www.coderclub.com.cn/img/beian.png # å…¬å®‰å›¾æ ‡ï¼ˆç»å¯¹è·¯å¾„ï¼‰
  PublicNetworkSecurity: é™•å…¬ç½‘å®‰å¤‡61011302001629å· # å…¬å®‰å¤‡æ¡ˆå·

# èœå•
menu:
  main:
    - identifier: search
      name: ğŸ”
      url: search
      weight: 1
    - identifier: home
      name: ä¸»é¡µ
      url: /
      weight: 2
    - identifier: posts
      name: æ–‡ç« 
      url: posts
      weight: 3
    - identifier: tags
      name: æ ‡ç­¾
      url: tags
      weight: 15
    - identifier: archives
      name: æ—¶é—´è½´
      url: archives
      weight: 20
    - identifier: about
      name: å…³äº
      url: about
      weight: 50
    - identifier: links
      name: å‹é“¾
      url: links
      weight: 60

# ä»£ç é«˜äº®é€‰é¡¹
markup:
  highlight:
    noClasses: false # æ˜¯å¦ä½¿ç”¨ç±»
    anchorLineNos: true # æ˜¯å¦æ˜¾ç¤ºè¡Œå·
    codeFences: true # æ˜¯å¦ä½¿ç”¨ä»£ç å—
    guessSyntax: true # æ˜¯å¦çŒœæµ‹è¯­æ³•
    lineNos: true # æ˜¯å¦æ˜¾ç¤ºè¡Œå·
    style: monokai # é£æ ¼ å¯é€‰å€¼ï¼šmonokai, manni, rrt, perldoc, borland, colorful, default, murphy, vs, trac, tango, fruity, autumn, bw, emacs, vim, pastie, friendly, native
